### ISSUE TITLE
Conflicting Dependencies problem when installing jupyterlab-drawio

### ISSUE THREAD

**Issue by lostdinar2** [QuantStack/jupyterlab-drawio#15]
Hello.I tried to install jupyterlab-drawio with the following command
jupyter labextension install jupyterlab-drawio

I got following error.How can I fix this?

Errored, use --debug for full output:
ValueError:
"jupyterlab-drawio@0.2.0" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab              Extension            Package
>=0.15.4-0 <0.16.0-0    >=0.16.2-0 <0.17.0-0 @jupyterlab/application
>=0.15.4-0 <0.16.0-0    >=0.16.2-0 <0.17.0-0 @jupyterlab/apputils
>=0.15.4-0 <0.16.0-0    >=0.16.2-0 <0.17.0-0 @jupyterlab/filebrowser
>=0.15.4-0 <0.16.0-0    >=0.16.2-0 <0.17.0-0 @jupyterlab/launcher

**Comment by wolfv** [comment]
did you upgrade your jupyterlab to 0.32.0 yet?

**Comment by lostdinar2** [comment]
Thanks, now fixed.
