### ISSUE TITLE
Added jupyterlab-drawio to awesome-jupyter

### ISSUE THREAD

**Issue by markusschanta** [QuantStack/jupyterlab-drawio#32]
Hi @gouarin @JohanMabille @maartenbreddels @martinRenou @rmenegaux @SylvainCorlay @wolfv,

Nice extension! FYI, I just added it to [awesome-jupyter](https://github.com/markusschanta/awesome-jupyter).

Cheers,
Markus

**Comment by wolfv** [comment]
Thanks a lot!
