### ISSUE TITLE
Automatically creating alternative document formats from .drawio files

### ISSUE THREAD

**Issue by psychemedia** [QuantStack/jupyterlab-drawio#38]
A recent release ([10.7.5](https://github.com/jgraph/drawio-desktop/releases/tag/v10.7.5)) of `draw.io` adds command line support that looks as if it lets you run export commands from the command line.

Picking up on [Jupytext](https://github.com/mwouts/jupytext), which uses the Jupyter content manager to maintain "paired" equivalents of documents (for example, an `.ipynb` notebook file and a markdown equivalent of it), I wonder if it would be useful to support a similar sort of behaviour for `jupyterlab-drawio` in which saving a drawio file also results in the automatic creation of an SVG exported version of it, for example?

To keep things tidy,, Jupytext allows you to set watchers on different directory paths so that files of a particular type updated in a specified directory are automatically dualled by equivalent documents of other file types in other directories (https://github.com/mwouts/jupytext/issues/180). In the drawio case, this might mean providing an `svg` directory into which `.svg` equivalent filed are automatically exported whenever a drawio file is saved?

**Comment by davidjgraph** [comment]
That's the desktop version, built with electron, you're not using that in Jupyter.

**Comment by psychemedia** [comment]
Ah... oops... I wonder if the original hacked command line route ([`drawio-batch`](https://github.com/languitar/drawio-batch)) would work then, although I guess it would add quite a bit of weight to the installation.
