### ISSUE TITLE
Jupyterlab file browser view is broken after installing jupyterlab-drawio

### ISSUE THREAD

**Issue by SKDoily** [QuantStack/jupyterlab-drawio#45]
I have a jupyterhub 1.0.0 running with jupyterlab 1.0.2.
After installing jupyterlab-drawio all entries in the file browser in jupyterlab are invisible. The gray background while hovering over a line with the mouse is about 1/3 of the original line height.
Clicking on different parts switches to the next folder or opens the selected file. Just the visibility is gone.

**Comment by SKDoily** [comment]
Hello I get the following error messages when activating the file browser. It is periodically repeated every now and then(~10-20s).

index.js:383 TypeError: Cannot read property 'icon' of undefined
    at Renderer.updateItemNode (listing.js:1439)
    at listing.js:662
    at Array.forEach (<anonymous>)
    at DirListing.onUpdateRequest (listing.js:659)
    at DirListing.push.FmDU.Widget.processMessage (widget.js:492)
    at invokeHandler (index.js:436)
    at sendMessage (index.js:172)
    at runMessageLoop (index.js:486)

**Comment by telamonian** [comment]
fixed in jupyterlab/jupyterlab#7192

After these changes are published, do a clean build:

```
jupyter lab clean
jupyter lab build
```

**Comment by SKDoily** [comment]
Working now with jupypterlab 1.1.4.
