### ISSUE TITLE
Compability to JupyterLab 2.0

### ISSUE THREAD

**Issue by belfhi** [QuantStack/jupyterlab-drawio#54]
Hello,
currently the extension is not compatible to JupyterLab 2.0,
could this be fixed?

**Comment by consideRatio** [comment]
It is fixed in master since #52, but we need a release as well beyond the current 0.6.0 release.

**Comment by parmentelat** [comment]
so in practical terms this means when ;-) ?

**Comment by miramar-labs** [comment]
any ETA on this release?

**Comment by wolfv** [comment]
I have just pushed a release to NPM (0.7.0) I hope this works :)

Sorry for the delay!

**Comment by consideRatio** [comment]
@wolfv I've tried it and it works great! Time to close the issue :tada:

**Comment by miramar-labs** [comment]
thanks!
