### ISSUE TITLE
Compatibility with jupyter lab Version 3.0.7

### ISSUE THREAD

**Issue by sam2332** [QuantStack/jupyterlab-drawio#75]
Can we get an update to allow the program to install on version 3.0.7

right now i get the following error when i try and install

```
F:\>jupyter labextension install jupyterlab-drawio
An error occured.
ValueError: The extension "jupyterlab-drawio" does not yet support the current version of JupyterLab.


Conflicting Dependencies:
JupyterLab              Extension      Package
>=3.0.4 <3.1.0          >=2.0.0 <3.0.0 @jupyterlab/application
>=3.0.3 <3.1.0          >=2.0.0 <3.0.0 @jupyterlab/apputils
>=5.0.2 <5.1.0          >=4.0.0 <5.0.0 @jupyterlab/coreutils
>=3.0.4 <3.1.0          >=2.0.0 <3.0.0 @jupyterlab/filebrowser
>=3.0.3 <3.1.0          >=2.0.0 <3.0.0 @jupyterlab/launcher
>=3.0.3 <3.1.0          >=2.0.0 <3.0.0 @jupyterlab/mainmenu
See the log file for details:  C:\Users\srudloff\AppData\Local\Temp\jupyterlab-debug-5g3r0i3i.log
<LogAttached>
```

[jupyterlab-debug-5g3r0i3i.log](https://github.com/QuantStack/jupyterlab-drawio/files/5961496/jupyterlab-debug-5g3r0i3i.log)

**Comment by SylvainCorlay** [comment]
Actually, for lab 3.0, the way to install jupyterlab-drawio is to use the pip or conda package.

@wolfv did we publish the npm package for the latest version?

**Comment by jtpio** [comment]
> @wolfv did we publish the npm package for the latest version?

It doesn't seem to be the case yet: https://www.npmjs.com/package/jupyterlab-drawio

![image](https://user-images.githubusercontent.com/591645/111450150-65ad1300-8710-11eb-8e2f-96c29c14d94d.png)

But we should publish it to `npm` anyway since it can be useful to others would like to extend the extension, or include it by default in an alternative JupyterLab distribution.

**Comment by jtpio** [comment]
Normally this should consist of running `npm publish` from the `0.8.0` tag:

https://github.com/QuantStack/jupyterlab-drawio/tree/0.8.0

**Comment by jtpio** [comment]
@sam2332 `0.8.0` was just published to `npm`: https://www.npmjs.com/package/jupyterlab-drawio/v/0.8.0

Which should make it possible to install the extension for JupyterLab 3.0 using the `jupyter labextension install` command.

Closing as fixed, but feel free to comment here or open a new issue if you have more questions. Thanks!
