### ISSUE TITLE
is there any way to read the shape and connection information in the drawio file

### ISSUE THREAD

**Issue by AronWaterAron** [QuantStack/jupyterlab-drawio#76]
is there any way to read the shape and connection information in the drawio file

**Comment by hbcarlos** [comment]
Hi @AronWaterAron, thanks for opening this issue.
The `dio` and `drawio` files are XML file. You could use an XML parser and get the information from the XML document.

Anyway, may the best place to ask this question is in the [drawio repository](https://github.com/jgraph/drawio)
