### ISSUE TITLE
Error during install

### ISSUE THREAD

**Issue by zemravi** [QuantStack/jupyterlab-drawio#8]
Error in installation. When I try to install using
$ jupyter labextension install jupyterlab-drawio

I get the following error. 

> /usr/local/bin/npm pack jupyterlab-drawio
jupyterlab-drawio-0.1.2.tgz

Errored, use --debug for full output:
IOError: CRC check failed 0x4231cfac != 0xc08de80bL

Would appreciate your help.
Thanks

**Comment by wolfv** [comment]
what is your npm & node version?

**Comment by zemravi** [comment]
nodejs v9.6.1
npm 5.6.0

**Comment by blink1073** [comment]
This looks like a Python error, what does `python -V` show?

**Comment by zemravi** [comment]
Python 2.7.14 :: Anaconda custom (64-bit)

Using the --debug option shows.. 

anaconda2/lib/python2.7/gzip.py", line 354, in _read_eof
    hex(self.crc)))

**Comment by blink1073** [comment]
I just tried with Python 2.7.14 on MacOS 10.13 and it worked fine, which OS are you using?

**Comment by zemravi** [comment]
Thanks for checking. 
I am using Ubuntu 16.04.

**Comment by wolfv** [comment]
You tried with two different OS and you get this error both times?

**Comment by blink1073** [comment]
I just tried with Anaconda Python 2.7.14 on Ubuntu 17.10 and didn't see the issue there either.   @zemravi, perhaps try this patch? https://stackoverflow.com/a/18602286

**Comment by wolfv** [comment]
Maybe there is an issue with a partially downloaded file? Could clearing
some npm or pip cache help?

Le 2 mars 2018 11:50 PM, "Steven Silvester" <notifications@github.com> a
écrit :

**Comment by SylvainCorlay** [comment]
Closing as outdated!
