### ISSUE TITLE
CommandToolbarButtonComponent for the toolbar items?

### ISSUE THREAD

**Issue by jtpio** [QuantStack/jupyterlab-drawio#83]
At the moment items are added to the toolbar as `DrawIOToolbarButton`:

https://github.com/QuantStack/jupyterlab-drawio/blob/e9260dd47c0f96fe16a0d5906a542e27f1551705/src/toolbar.tsx#L8

Here:

https://github.com/QuantStack/jupyterlab-drawio/blob/e9260dd47c0f96fe16a0d5906a542e27f1551705/src/editor.ts#L205-L239

Question: are all the items mapped to a `drawio:command`? If so is it possible to use the built-in `CommandToolbarButtonComponent`?

If not then it's fine and we can just close this issue (it was mostly to double check)

https://github.com/jupyterlab/jupyterlab/blob/4e6cbf24489b109532dc8ba933321b73b28884f1/packages/apputils/src/toolbar.tsx#L606

cc @hbcarlos who might have more insight about this

**Comment by hbcarlos** [comment]
Yes, I think they are all as a command too. I need to check but anyway we can create a command if one of them is missing.
